{
 "title": "Product Sync Metrics",
 "refresh": "30s",
 "panels": [
  {
   "title": "Últimos produtos sincronizados",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "product_sync_last_fetched_count"
    }
   ]
  },
  {
   "title": "Total de Execuções",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "product_sync_execution_count" }
   ]
  },
  {
   "title": "Sucessos na Sincronização",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "product_sync_success_count" }
   ]
  },
  {
   "title": "Falhas na Sincronização",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "product_sync_failure_count" }
   ]
  },
  {
   "title": "API Calls Sucesso",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "product_api_call_success_total" }
   ]
  },
  {
   "title": "API Calls Falhas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "product_api_call_failure_total" }
   ]
  }
 ]
}